### ISSUE TITLE
Make the relative path support in BlobName

### ISSUE THREAD

**Issue by GalayM** [2020IP/TwentyTwenty.Storage#17]
Make the relative path support in BlobName for local storage.

For example: "somePatch/test.txt"
Works for Azure, a folder will be created and a file will be created in it.
Locally - does not work.

**Comment by GalayM** [comment]
How can I fix this problem myself?

**Comment by junghandy** [comment]
+1 

Ran into this issue today as well. I'm using the library to switch between disk and Azure Blob file storage and can only get one to work at a time depending on the parameters.

There's a difference between the usage of the container name between `AzureStorageProvider` and `LocalStorageProvider`. `AzureStorageProvider` expects the container name to be the container name and the blob name to the path to the file, whereas `LocalStorageProvider` expects the container name to be the path to the folder and the blob name to be the filename.

When using `LocalStorageProvider`, `SaveBlobStreamAsync("c:/whatever", "path/to/file.txt")` throws an error on the `File.Create()` because the previous call to `Directory.CreateDirectory()` only creates the base folder + container name.

**Comment by jarroda** [comment]
This is fixed in version 2.7.0, which is now on nuget.
